name: petitpal
description: Voice-first assistant for adults 65+
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Firebase (Analytics & Crashlytics) - VERIFIED COMPATIBLE VERSIONS
  firebase_core: ^3.15.2
  firebase_analytics: ^11.3.0  
  firebase_crashlytics: ^4.3.6
  
  # Voice & Speech
  speech_to_text: ^7.3.0
  flutter_tts: ^4.1.0
  permission_handler: ^12.0.1
  
  # Storage & Preferences
  shared_preferences: ^2.3.3
  
  # HTTP & API
  http: ^1.2.2
  
  # Deep Links & Sharing
  app_links: ^6.4.1
  share_plus: ^7.2.2
  
  # Device Information
  device_info_plus: ^10.1.0
  
  # UI & Animations
  flutter_animate: ^4.5.2
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets for JSON-driven themes and configuration
  assets:
    - assets/themes/
    - assets/config/
    - assets/audio/