name: petitpal
description: Voice-first assistant for seniors with Cloudflare Worker backend
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^10.0.0
  http: ^1.2.2
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  app_links: ^6.3.2
  url_launcher: ^6.3.0
  speech_to_text: ^7.1.0
  flutter_tts: ^3.8.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  flutter_animate: ^4.5.0
  simple_animations: ^5.0.2
  intl: ^0.19.0
  cryptography: ^2.7.0
  sentry_flutter: ^8.7.0
  firebase_core: ^3.4.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
